export const FETCHWEATHER_START = 'FETCHWEATHER_START';
export const FETCHWEATHER_SUCCESS = 'FETCHWEATHER_SUCCESS';
export const FETCHWEATHER_FAILURE = 'FETCHWEATHER_FAILURE';

export const FETCHCITY_START = 'FETCHCITY_START';
export const FETCHCITY_SUCCESS = 'FETCHCITY_SUCCESS';
export const FETCHCITY_FAILURE = 'FETCHCITY_FAILURE';